name = input("이름을 입력하세요: ")
num = input("학번을 입력하세요: ")
major =input("학과를 입력하세요: ")
school =input("학교를 입력하세요: ")
print("<출력>\n"+f"이름: {name}")
print(f"학번: {num}")
print(f"학과: {major}")
print(f"학교: {school}")